import React from "react";
import Head from "next/head";
import Image from "next/image";
import Styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer"; 
import profilePic from "../public/hero (1).png";
import logoDev from "../public/dev.svg";
import logoGraph from "../public/graph.svg";
import logoLaptop from "../public/laptop.svg";
import Link from "next/link";
import SlideHome from "../components/SlideHome";
import { BsArrowRight } from "@react-icons/all-files/bs/BsArrowRight";
import FormTel from "../components/FormTel";
import MultiSlider from "../components/Testiomnial";
import { motion } from "framer-motion";
import  {sanityClient,UrlFor}  from "../lib/sanity"
const recipesQuery=`*[_type== "homepage"]{
  "TestimonialCaroussel":*[_type== "testimonial"]{
  content,
  photo,
  author
},
  arrayCaroussel,
  photohero,
  texthero,
  titlehero,
  "section":*[_type== "section"]{
    title,
  content,
  photo,
  
}
  
}`
export async function getServerSideProps() {
  // Fetch data from external API
  const recipies = await sanityClient.fetch(recipesQuery)

  // Pass data to the page via props
  return { props: { recipies } };
}


export default function Home({recipies}) {
  return (
    <div className="containerApp ">

      <Head>
        <title>DigitYourDream</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="backgroundWebsite">
      <header>
      <Navbar />
      </header>
      <main className="">
     
        <section className="container mx-auto  lg:ml-10 lg:px-16 mt-20">
          <div className="lg:mt-24 flex flex-col-reverse justify-center lg:flex-row  pb-10 mt-8 ">
            <motion.div 
                initial={{x:-200, opacity:0}} 
                transition={{duration:1.2,}}
                whileInView={{opacity:1,x:0}}
                viewport={{once:true}} className="flex flex-1 flex-col items-center md:items-start mt-28 lg:mt-10 space-y-6 lg:space-y-8">
              <h1 className="text-4xl px-4  lg:px-0 md:text-xl lg:text-7xl font-bold text-start text-white flex-nowrap ">
             {recipies[0].titlehero}
              </h1>
              <div className="px-4 lg:px-0 lg:w-4/5">
                <p className="text-start lg:text-xl text-white  ">
              {recipies[0].texthero}
                 
                </p>
              </div>
           <FormTel/>
            </motion.div >
            <div className="flex justify-center flex-1 hidden lg:block pb-2 lg:pb-12">
              <motion.img
          initial={{y:-200, opacity:0}} 
          transition={{duration:1.2,}}
          whileInView={{opacity:1,y:0}}
          viewport={{once:true}} src={UrlFor(recipies[0].photohero).url()} className="lg:-mt-10 " />
            </div>
          </div>
        </section>
      </main>
      </div>
   
<SlideHome props={recipies[0].arrayCaroussel} /> 
  
      <section className="bg-[#F9F9F9] lg:px-7 py-8 lg:py-16">
        <div className="container mx-auto flex flex-row flex-wrap justify-start  xl:justify-center  lg:p-4 items-stretch gap-2 ">
          <motion.div 
                initial={{y:-300, opacity:0}} 
                transition={{duration:1.2,}}
                whileInView={{opacity:1,y:0}}
                viewport={{once:true}} 
                className="flex flex-col m-5 lg:m-10 max-w-sm md:max-w-xs xl:max-w-sm box-border">
            <div className="">
              <Image
                src={logoDev}
                className="lg:h-5/6"
                width={25}
                height={25}
                alt="logo design"
              />
            </div>
            <div className="mt-2">
              <p className="block-text">
                <span className="font-bold">
                Stratégie & conception.
                </span>
                Nous commençons par une prise en main de votre projet afin de plonger dans votre univers.
Ensemble, nous mettons en pratique vos idées dans le but d’en faire une solution digital.

              </p>
            </div>
            <div className="flex flex-row items-center text-blue-600	 hover:gap-2 mt-3">
            <p className="underline underline-offset-4"><Link href="/" >Demander un devis</Link></p> 
              <BsArrowRight />
            </div>
          </motion.div>
          <motion.div
            initial={{y:-200, opacity:0}} 
            transition={{duration:1.2,}}
            whileInView={{opacity:1,y:0}}
            viewport={{once:true}}   className="flex flex-col m-5 lg:m-10 max-w-sm md:max-w-xs xl:max-w-sm box-border">
            <div className="">
              <motion.img
                src={logoGraph}
                className="lg:h-5/6"
                width={25}
                height={25}
                alt="logo design"
              />
            </div>
            <div className="mt-2">
              <p className="block-text tex-sm">
                <span className="font-bold">
                Développement sur mesure.
                </span>
                Nous collaborons avec vous en devenant votre équipe tech pour vous accompagner et vous conseiller techniquement.
Nous privilégions les solutions open sources fiables selon le besoin de votre projet : React / Symfony / Laravel / Node JS / React / Next JS / et des solutions innovantes comme les CMS headless (Strapi, Sanity, ...) .

              </p>
            </div>
            <div className="flex flex-row items-center mt-3 text-blue-600	 hover:gap-2 hover:duration-1000">
             <p className="underline underline-offset-4"><Link href="/" >Demander un devis</Link></p> 
              <BsArrowRight />
            </div>
          </motion.div>
          <motion.div
             initial={{y:-100, opacity:0}} 
             transition={{duration:1.2,}}
             whileInView={{opacity:1,y:0}}
             viewport={{once:true}} 
             className="flex flex-col m-5 lg:m-10 max-w-sm md:max-w-xs xl:max-w-sm box-border">
            <div className="">
              <Image
                src={logoLaptop}
                className="lg:h-5/6"
                width={25}
                height={25}
                alt="logo design"
              />
            </div>
            <div className="mt-2 ">
              <p className="block-text">
                <span className="font-bold">
                Accompagnement & conseil.
                </span>
                Pour assurer le succès de votre produit digital,
                 nous tâchons de comprendre vos enjeux business et de clarifier les objectifs auxquels va devoir répondre le produit.
              </p>
            </div>
            <div className="flex flex-row items-center mt-3 text-blue-600	hover:gap-2 transition duration-300  ">
            <p className="underline underline-offset-4"><Link href="/" >Demander un devis</Link></p> 
              <BsArrowRight />
            </div>
          </motion.div>
        </div>
      </section>

      <section className="lg:p-5 p-1">
        <div className="lg:my-0 mb-6  mx-auto flex flex-col flex-wrap items-center  lg:text-start justify-center xl:flex-row xl:gap-16 p-0">
          <div className="max-w-xl px-5 lg:px-0 lg:m-10">
           <motion.img
          initial={{x:-200, opacity:0}} 
          transition={{duration:1.2,}}
          whileInView={{opacity:1,x:0}}
          viewport={{once:true}} src={UrlFor(recipies[0].section[0].photo).url()} width={500} height={500} className=""   alt="logo design"/>

          </div>
          <motion.div initial={{opacity:0}} 
    whileInView={{opacity:1}}
    transition={{duration:1.5}} className="flex flex-col items-center lg:items-start max-w-xl m-4 lg:m-10">
            <h2 className="text-3xl lg:text-4xl	font-semibold ">
             {recipies[0].section[0].title}
            </h2>
            <div className="my-5 flex flex-col gap-4">
              <p className="leading-9">
            {recipies[0].section[0].content}
              </p>
            </div>
            <div className="flex ">
            <button className="btn btn-blue mt-1">Contactez-nous</button>
            </div>
          </motion.div>
        </div>
      </section>

      <section className="bg-[#F9F9F9] lg:p-5 p-1 ">
        <div className="lg:my-0 mb-6 lg:mb-0 mx-auto flex flex-col-reverse flex-wrap items-center justify-start xl:justify-center xl:flex-row xl:gap-16 p-0">
         <motion.div initial={{opacity:0}} 
    whileInView={{opacity:1}}
    transition={{duration:1.5}}  className=" flex flex-col items-center lg:items-start max-w-xl m-4 lg:m-10">
            <h2 className="text-3xl lg:text-4xl	font-semibold ">
            {recipies[0].section[1].title}
            </h2>
            <div className="my-5 flex flex-col gap-4">
              <p className="leading-9">
              {recipies[0].section[1].content}
              </p>
            </div>
            <button className="btn btn-blue mt-1 ">Contactez-nous</button>
          </motion.div>
          <div className="max-w-xl mx-1 lg:m-10">
            <motion.img
          initial={{x:200, opacity:0}} 
          transition={{duration:1.2,}}
          whileInView={{opacity:1,x:0}}
          viewport={{once:true}} src={UrlFor(recipies[0].section[1].photo).url()} width={500} height={500} className=""   alt="logo design"/>
          </div>
        </div>
      </section>
      <section className="lg:p-10">
        <div className="md:py-10 md:px-20">
          <div className="mt-10 lg:mt-5 ">
            <h2 className="text-3xl lg:text-3xl	font-semibold text-center tracking-[2px]">
              Comment Aidons-Nous Les Gens
            </h2>
           <MultiSlider props={recipies[0].TestimonialCaroussel} />
      
          </div>
        </div>
      </section>
 <Footer/>
    
    </div>
  );
}
