import Head from 'next/head'
import Image from 'next/image'
import Styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import profilePic from '../public/hero (1).png'
import SlideHome from '../components/SlideHome'
import { BsArrowRight  } from '@react-icons/all-files/bs/BsArrowRight';
import React from 'react';

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http:/localhost:4000/image`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}

export default function Home(props) {
  
  return (
    <>
      {console.log(props)}
    
      <Head>
        <title>DigigitYourDream</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main className={Styles.backgroundHome }>
      <Navbar/>
      <section className='relative container mx-auto lg:ml-10 lg:px-10 '>
      <div className=" flex flex-col-reverse justify-center  lg:-space-x-40 lg:flex-row  lg:mt-10 lg:mb-10 ">
          <div className="flex flex-1 flex-col items-center lg:items-start lg:mt-10 z-50 ">
          <h1 className="text-xxl md:text-xl lg:text-7xl font-bold text-start text-white flex-nowrap	">Développement de 
                   logiciel sur mesure pour PME</h1>
                   <div className=' w-4/5'>
                   <p className='text-start text-xl text-white my-8'>  De la petite entreprise au plus importante 
                startup nous nous ocuppons de vos projets digital
                Application web, logiciel surmesure,plateformes en ligne..</p>
                </div>
                <div className='flex  flex-wrap gap-6'>
                <form onSubmit={"this.handleSubmit"}>
        <label className="">
          <input type="text" value={""} onChange={"this.handleChange"} placeholder="+33 65 1..." className="focus:outline-blue-600 py-3 px-6 px-6 rounded-l-md mr-2 shadow-xl"/>
        </label>
        <button className='shadow-xl py-3 px-6 rounded-r-md transition duration-300 bg-neutral-800	 text-white' type="submit" value="Submit" >Devis Maintenant</button>
      </form>
              
          </div>
          </div>
         <div className='flex justify-center flex-1'>
         <Image src={profilePic} className="lg:h-4/5 mb-20"  />
         </div>
      </div>

     </section>
     
     </main>
      
      <SlideHome props={props.data}/>
    <section className='container mx-auto grid grid-cols-3 '>
      <div className=''>
        <div  className=''>
        <Image src={profilePic} className="lg:h-5/6" width={90} height={60}  />
        </div>
        <div  className='lg:w-4/6'>
          <p  className='block-text'>
          AVOIR UNE Aide pour votre projet.Soyez visible à chaque étape du parcours utilisateur de vos prospects et transformez-les en nouveaux clients.
Une stratégie en référencement naturel adaptée à vos objectifs Business
          </p>
        </div>
        <div  className=''>
          <p  className=''>
          Demander un devis
          </p>
          <BsArrowRight/>
        </div>
      </div>
      <div className=''> <div  className=''>
      <Image src={profilePic} className="lg:h-5/6" width={90} height={60}  />
        </div>
        <div  className='lg:w-4/6'>
          <p  className='block-text'>
          AVOIR UNE Aide pour votre projet.Soyez visible à chaque étape du parcours utilisateur de vos prospects et transformez-les en nouveaux clients.
Une stratégie en référencement naturel adaptée à vos objectifs Business
          </p>
        </div>
        <div  className=''>
          <p  className=''>
          Demander un devis
          </p>
          <BsArrowRight/>
        </div></div>
      <div className=''> <div  className=''>
        <Image src={profilePic} className="lg:h-5/6" width={90} height={60}  />
        </div>
        <div  className='lg:w-4/6'>
          <p  className='block-text'>
          AVOIR UNE Aide pour votre projet.Soyez visible à chaque étape du parcours utilisateur de vos prospects et transformez-les en nouveaux clients.
Une stratégie en référencement naturel adaptée à vos objectifs Business
          </p>
        </div>
        <div  className=''>
          <p  className=''>
          Demander un devis
          <BsArrowRight/>
          </p>
        
        </div></div>
    </section>
 <div className=''>
  <div className=''>
   
    <div className={Styles.carrouselHome}>
    
    </div>
  </div>

 </div>
 <p className="decoration-rose-700">titre tailwind</p>

      <footer className="">
       
      </footer>
    </>
  )
}
